name = "docbuild"
defaultTargets = [
  "Chemistry",
  "Existence",
  "Irrational",
  "Mathematics",
  "Physics",
  "Structure",
]

reservoir = false
version = "0.1.0"
packagesDir = "../.lake/packages"

[leanOptions]
maxHeartbeats = 0

[[require]]
scope = "leanprover"
name = "doc-gen4"
rev = "v4.32.0"

[[require]]
name = "Existence"
path = "../"

[[require]]
name = "Irrational"
path = "../"

[[require]]
name = "Mathematics"
path = "../"

[[require]]
name = "Physics"
path = "../"

[[require]]
name = "Structure"
path = "../"
