name = "Irrational"
version = "0.1.0"
defaultTargets = [
  "Chemistry",
  "Existence",
  "Irrational",
  "Scrapbook",
  "Structure",
]

[[lean_lib]]
name = "Chemistry"
globs = ["Chemistry.+"]

[[lean_lib]]
name = "Existence"
globs = ["Existence.+"]

[[lean_lib]]
name = "Irrational"
globs = ["Irrational.+"]

[[lean_lib]]
name = "Scrapbook"
globs = ["Scrapbook.+"]

[[lean_lib]]
name = "Structure"
globs = ["Structure.+"]

[[require]]
name = "Mathlib"
scope = "leanprover-community"
rev = "v4.32.0"

# [[require]]
# name = "plausible"
# scope = "leanprover-community"
