name = "Irrational"
version = "0.1.0"
defaultTargets = ["Irrational", "Scrapbook"]

[[lean_lib]]
name = "Irrational"
globs = ["Irrational", "Irrational.+"]

[[lean_lib]]
name = "Scrapbook"
globs = ["Scrapbook", "Scrapbook.+"]

[[require]]
name = "Mathlib"
scope = "leanprover-community"
rev = "v4.32.0"
